import { Prompt } from "./types";

export const prompts: Prompt[] = [
  {
    id: "1",
    title: "Technical Blog Post Writer",
    description: "Generate a well-structured technical blog post with code examples and clear explanations.",
    prompt: "Write a comprehensive technical blog post about [TOPIC]. Include:\n- An engaging introduction that explains why this matters\n- Clear section headings\n- Code examples with explanations\n- Real-world use cases\n- A conclusion with next steps\n\nTarget audience: [AUDIENCE_LEVEL] developers.\nTone: Professional but approachable.\nLength: approximately [WORD_COUNT] words.",
    platforms: ["chatgpt", "claude", "gemini"],
    category: "writing",
    tags: ["blog", "technical", "content"],
    complexity: "intermediate",
    popularity: 5,
  },
  {
    id: "2",
    title: "Code Review Assistant",
    description: "Get thorough code reviews with actionable suggestions for improvement.",
    prompt: "Review the following code and provide feedback on:\n1. Code quality and readability\n2. Potential bugs or edge cases\n3. Performance implications\n4. Security concerns\n5. Suggested improvements with examples\n\nCode:\n```\n[PASTE_CODE_HERE]\n```\n\nLanguage/Framework: [LANGUAGE]\nContext: [WHAT_THE_CODE_DOES]",
    platforms: ["claude", "chatgpt", "copilot"],
    category: "coding",
    tags: ["code-review", "quality", "debugging"],
    complexity: "intermediate",
    popularity: 5,
  },
  {
    id: "3",
    title: "Academic Research Synthesizer",
    description: "Synthesize research findings from multiple sources into a coherent analysis.",
    prompt: "I'm researching [TOPIC] for a [PURPOSE]. Please help me:\n\n1. Identify the key themes and findings across these sources\n2. Note areas of consensus and disagreement\n3. Highlight methodological strengths and limitations\n4. Suggest gaps in the current research\n5. Provide a structured synthesis\n\nSources/findings to synthesize:\n[PASTE_SOURCES]\n\nFormat the output as a structured academic summary with citations.",
    platforms: ["claude", "perplexity", "gemini"],
    category: "research",
    tags: ["academic", "synthesis", "analysis"],
    complexity: "advanced",
    popularity: 4,
  },
  {
    id: "4",
    title: "Brand Story Generator",
    description: "Create compelling brand narratives that resonate with target audiences.",
    prompt: "Create a brand story for [BRAND_NAME] that:\n\nBrand details:\n- Industry: [INDUSTRY]\n- Mission: [MISSION]\n- Target audience: [AUDIENCE]\n- Unique value: [VALUE_PROP]\n\nThe story should include:\n1. Origin narrative (the why)\n2. The problem we saw in the world\n3. Our approach and philosophy\n4. Customer transformation journey\n5. Vision for the future\n\nTone: [TONE]\nLength: [LENGTH]",
    platforms: ["chatgpt", "claude"],
    category: "creative",
    tags: ["branding", "storytelling", "marketing"],
    complexity: "intermediate",
    popularity: 4,
  },
  {
    id: "5",
    title: "SWOT Analysis Framework",
    description: "Generate a comprehensive SWOT analysis for strategic business planning.",
    prompt: "Conduct a detailed SWOT analysis for [COMPANY/PROJECT].\n\nContext:\n- Industry: [INDUSTRY]\n- Company size: [SIZE]\n- Current position: [MARKET_POSITION]\n- Key competitors: [COMPETITORS]\n\nFor each quadrant, provide:\n- 5-7 specific, actionable points\n- Supporting evidence or reasoning\n- Priority ranking (high/medium/low)\n\nConclude with:\n- Top 3 strategic recommendations\n- Quick wins vs. long-term plays\n- Risk mitigation priorities",
    platforms: ["chatgpt", "claude", "gemini"],
    category: "business",
    tags: ["strategy", "analysis", "planning"],
    complexity: "intermediate",
    popularity: 5,
  },
  {
    id: "6",
    title: "Interactive Lesson Plan Builder",
    description: "Design engaging lesson plans with activities and assessments.",
    prompt: "Design a lesson plan for teaching [TOPIC] to [GRADE_LEVEL/AUDIENCE].\n\nRequirements:\n- Duration: [TIME]\n- Learning objectives: [OBJECTIVES]\n- Prior knowledge assumed: [PREREQUISITES]\n\nInclude:\n1. Warm-up activity (5 min)\n2. Main instruction with interactive elements\n3. Hands-on practice activity\n4. Group discussion questions\n5. Assessment method\n6. Differentiation strategies for varied learners\n7. Take-home extension activity\n\nMake it engaging and inclusive.",
    platforms: ["chatgpt", "claude", "gemini"],
    category: "education",
    tags: ["lesson-plan", "teaching", "curriculum"],
    complexity: "intermediate",
    popularity: 4,
  },
  {
    id: "7",
    title: "Data Pipeline Architect",
    description: "Design data processing pipelines with clear specifications.",
    prompt: "Design a data pipeline for [USE_CASE].\n\nData sources:\n- [SOURCE_1]: [FORMAT], [VOLUME], [FREQUENCY]\n- [SOURCE_2]: [FORMAT], [VOLUME], [FREQUENCY]\n\nRequirements:\n- Latency target: [LATENCY]\n- Data quality rules: [RULES]\n- Output format: [FORMAT]\n- Scale: [SCALE]\n\nProvide:\n1. Architecture diagram (text-based)\n2. Technology recommendations with justification\n3. Data transformation steps\n4. Error handling strategy\n5. Monitoring and alerting approach\n6. Cost estimation framework",
    platforms: ["claude", "chatgpt", "copilot"],
    category: "data-analysis",
    tags: ["pipeline", "architecture", "ETL"],
    complexity: "advanced",
    popularity: 3,
  },
  {
    id: "8",
    title: "Regex Pattern Crafter",
    description: "Generate and explain regex patterns for complex text matching.",
    prompt: "Create a regex pattern that matches [DESCRIPTION_OF_PATTERN].\n\nExamples of strings that SHOULD match:\n- [EXAMPLE_1]\n- [EXAMPLE_2]\n\nExamples that should NOT match:\n- [COUNTER_EXAMPLE_1]\n- [COUNTER_EXAMPLE_2]\n\nPlease provide:\n1. The regex pattern\n2. Step-by-step breakdown of each component\n3. Edge cases it handles\n4. Edge cases it might miss\n5. Test cases in [LANGUAGE]",
    platforms: ["chatgpt", "claude", "copilot"],
    category: "coding",
    tags: ["regex", "patterns", "text-processing"],
    complexity: "intermediate",
    popularity: 4,
  },
  {
    id: "9",
    title: "Fact-Check Research Query",
    description: "Verify claims with structured evidence from multiple angles.",
    prompt: "Fact-check the following claim: \"[CLAIM]\"\n\nPlease:\n1. Rate confidence level (verified / likely true / uncertain / likely false / false)\n2. Provide supporting evidence with sources\n3. Provide contradicting evidence if any\n4. Note important context or nuances\n5. Identify what additional information would be needed for full verification\n6. Suggest related claims worth investigating",
    platforms: ["perplexity", "gemini", "claude"],
    category: "research",
    tags: ["fact-check", "verification", "sources"],
    complexity: "beginner",
    popularity: 5,
  },
  {
    id: "10",
    title: "Short Story from Constraints",
    description: "Generate creative short stories from specific creative constraints.",
    prompt: "Write a short story with these constraints:\n\n- Genre: [GENRE]\n- Setting: [SETTING]\n- Must include: [ELEMENT_1], [ELEMENT_2], [ELEMENT_3]\n- Narrative perspective: [POV]\n- Emotional arc: [ARC]\n- Word count: approximately [COUNT]\n\nAdditional rules:\n- The opening line must [OPENING_CONSTRAINT]\n- There should be exactly one plot twist\n- End with [ENDING_TYPE]\n\nPrioritize vivid sensory details and authentic dialogue.",
    platforms: ["claude", "chatgpt"],
    category: "creative",
    tags: ["fiction", "storytelling", "constraints"],
    complexity: "beginner",
    popularity: 4,
  },
  {
    id: "11",
    title: "API Endpoint Designer",
    description: "Design RESTful or GraphQL API endpoints with full specifications.",
    prompt: "Design API endpoints for a [TYPE] service that handles [DOMAIN].\n\nRequirements:\n- API style: [REST/GraphQL]\n- Authentication: [AUTH_METHOD]\n- Key entities: [ENTITIES]\n\nFor each endpoint, provide:\n1. HTTP method and URL pattern\n2. Request headers and body schema\n3. Response schema with status codes\n4. Validation rules\n5. Rate limiting recommendations\n6. Example request and response\n\nFollow [STANDARD] conventions and include pagination strategy.",
    platforms: ["claude", "chatgpt", "copilot"],
    category: "coding",
    tags: ["API", "design", "backend"],
    complexity: "advanced",
    popularity: 4,
  },
  {
    id: "12",
    title: "Email Campaign Sequence",
    description: "Create multi-email marketing sequences with personalization.",
    prompt: "Create a [NUMBER]-email marketing sequence for [PRODUCT/SERVICE].\n\nAudience: [AUDIENCE]\nGoal: [CONVERSION_GOAL]\nBrand voice: [VOICE]\n\nFor each email provide:\n1. Subject line (+ 2 A/B alternatives)\n2. Preview text\n3. Email body with personalization tokens\n4. CTA button text and placement\n5. Optimal send timing\n6. Segmentation criteria\n\nSequence should follow: awareness → interest → desire → action.\nInclude re-engagement branch for non-openers.",
    platforms: ["chatgpt", "claude"],
    category: "business",
    tags: ["email", "marketing", "copywriting"],
    complexity: "intermediate",
    popularity: 3,
  },
  {
    id: "13",
    title: "Dataset Explorer",
    description: "Analyze and summarize datasets with statistical insights.",
    prompt: "Analyze this dataset and provide:\n\n1. Summary statistics for each column\n2. Data quality assessment (missing values, outliers, inconsistencies)\n3. Distribution analysis for key variables\n4. Correlation matrix and notable relationships\n5. Three interesting patterns or insights\n6. Recommended visualizations\n7. Suggested next steps for deeper analysis\n\nDataset description: [DESCRIPTION]\nColumns: [COLUMNS]\nSample data:\n[SAMPLE_DATA]\n\nPresent findings in a clear, non-technical summary followed by technical details.",
    platforms: ["chatgpt", "claude", "gemini"],
    category: "data-analysis",
    tags: ["statistics", "EDA", "insights"],
    complexity: "intermediate",
    popularity: 4,
  },
  {
    id: "14",
    title: "Socratic Tutor",
    description: "Learn through guided questioning rather than direct answers.",
    prompt: "Act as a Socratic tutor for [SUBJECT]. I want to understand [CONCEPT].\n\nRules:\n- Never give the answer directly\n- Ask guiding questions that lead me to discover the answer\n- Start with what I already know and build from there\n- If I'm stuck, provide a hint rather than the solution\n- Celebrate correct reasoning\n- Correct misconceptions gently with counter-examples\n- Adjust difficulty based on my responses\n\nMy current understanding: [CURRENT_LEVEL]\n\nLet's begin. Ask me your first question.",
    platforms: ["claude", "chatgpt"],
    category: "education",
    tags: ["learning", "socratic", "tutoring"],
    complexity: "beginner",
    popularity: 5,
  },
  {
    id: "15",
    title: "Meeting Notes to Actions",
    description: "Transform raw meeting notes into structured action items and summaries.",
    prompt: "Transform these meeting notes into a structured summary:\n\n[PASTE_NOTES]\n\nProvide:\n1. Meeting summary (3-4 sentences)\n2. Key decisions made\n3. Action items table:\n   | Action | Owner | Deadline | Priority |\n4. Open questions requiring follow-up\n5. Topics deferred to next meeting\n6. Dependencies between action items\n\nFormat for sharing via [EMAIL/SLACK/DOCUMENT].",
    platforms: ["chatgpt", "claude", "gemini", "copilot"],
    category: "business",
    tags: ["meetings", "productivity", "organization"],
    complexity: "beginner",
    popularity: 5,
  },
  {
    id: "16",
    title: "World-Building Framework",
    description: "Create rich fictional worlds with consistent internal logic.",
    prompt: "Build a fictional world with these parameters:\n\n- Genre: [GENRE]\n- Tech level: [TECH_LEVEL]\n- Core conflict: [CONFLICT]\n- Unique element: [UNIQUE_FEATURE]\n\nDetail the following:\n1. Geography and climate (with map description)\n2. Major cultures and their values\n3. Political systems and power dynamics\n4. Economy and trade\n5. Magic/technology system with rules and limitations\n6. History timeline (5 key events)\n7. Three potential story hooks\n\nEnsure internal consistency across all elements.",
    platforms: ["claude", "chatgpt"],
    category: "creative",
    tags: ["worldbuilding", "fiction", "games"],
    complexity: "advanced",
    popularity: 3,
  },
];
